### ISSUE TITLE
Contact Form Issue

### ISSUE THREAD

**Issue by EmaanFarhat** [AlpayC/portfolio_site#10]
Hy Alpay How does the contact form works because in mine it does not work and what is the APIBASEURL? 
@AlpayC    @alvin-dennis
![image](https://github.com/AlpayC/portfolio_site/assets/113349013/e3b70ade-f9e8-4a30-aef8-fda0575f9e40)

**Comment by AlpayC** [comment]
Hey , you can build the  backend with nodemailer to establish a connection between frontend and backend.

The APIBASEURL is for development purposes mon render.com

**Comment by EmaanFarhat** [comment]
Can you explain in detail?
