### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jklaze** [AlpayC/portfolio_site#5]
Hello, is this open source? Can I use this code to create my portfolio?

**Comment by Waroach** [comment]
Yes, it seems to be open source and free to use. I stumbled upon it while searching for free templates, and the fact that there's no license file in the repository further suggests that it was uploaded for others to utilize. You should be good to go!

https://reactjsexample.com/a-portfolio-website-built-using-react-tailwind-css-and-typescript/

**Comment by AlpayC** [comment]
> Yes, it seems to be open source and free to use. I stumbled upon it while searching for free templates, and the fact that there's no license file in the repository further suggests that it was uploaded for others to utilize. You should be good to go!
> 
> https://reactjsexample.com/a-portfolio-website-built-using-react-tailwind-css-and-typescript/
> 

Hey buddy sorry for my late response. 

Yeah of course. You can use it for your own portfolio.

Greetings from Germany
