### ISSUE TITLE
api configuration

### ISSUE THREAD

**Issue by alvin-dennis** [AlpayC/portfolio_site#7]
Hi could you brief me about configuring the [api-base-url] and [api-service statusurl]. how did you make it?
Can you help me to make it by describing the steps or providing necessary docs?
@AlpayC

**Comment by AlpayC** [comment]
Hey, I reference this to my answer in [https://github.com/AlpayC/portfolio_site/issues/9](https://github.com/AlpayC/portfolio_site/issues/9)
