### ISSUE TITLE
radial gradient config

### ISSUE THREAD

**Issue by alvin-dennis** [AlpayC/portfolio_site#8]
Hi, can you brief and tell me the code needed to get the output like the one below made by you?
the code needed for the radial gradient text of the subtitle as well as the waving symbol.
Tested so many commands but there's no use. No change in the final output
<img width="687" alt="Screenshot 2024-01-16 004130" src="https://github.com/AlpayC/portfolio_site/assets/134829236/9ac928d9-c27c-4a66-84c5-acaa684ad9ee">
@AlpayC

**Comment by HeyFatimah** [comment]
Hy He Did everything in the separate Private repository

**Comment by HeyFatimah** [comment]
@alvin-dennis  Hy Use This class in index.css to get the radial gradient
`.text-animation{background:linear-gradient(to right,var(--lightblue) 20%,var(--orange) 40%,var(--lightblue) 70%,var(--orange) 80%);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;background-size:500% auto;animation:textShine 5s ease-in-out infinite alternate}@keyframes textShine{0%{background-position:0 50%}to{background-position:100% 50%}}`
Regards

**Comment by alvin-dennis** [comment]
ok. No problem. I had already left that
