### ISSUE TITLE
Need the Api Configuration

### ISSUE THREAD

**Issue by HeyFatimah** [AlpayC/portfolio_site#9]
Hi, Alpay in your documentation there is API_BASE_URL and Other Api 
How did you do that? Can you explain

**Comment by alvin-dennis** [comment]
He did that by creating separate backend for the email and the service status services. I think
@HeyFatimah

**Comment by HeyFatimah** [comment]
Can you give me idea like how can i do that using mongoDB

**Comment by HeyFatimah** [comment]
I Used Mongo DB Api on this but the email does not work

(https://portfolio-site-nine-beta.vercel.app/)

Can you check in your local?

**Comment by alvin-dennis** [comment]
@HeyFatimah I used a service status iframe code. Check mine and u will know. Also we can disable the translation switch in the navbar

**Comment by HeyFatimah** [comment]
I dont want to disble the translation switch i just want to use the contact form
Can you help me with that?

**Comment by AlpayC** [comment]
Hey guys, the api base url is only for development purposes and points to the local url on render.com, where the backend was deployed.

So it's for the backend. The backend is small server builds with node js +express+ nodemailer.

You don't need mongodb for that purpose. 


The service api points [betterstack.com](https://betterstack.com). You can sign up for free and builds your own uptime monitor for your services.

Actually I don't use react anymore for my website. It's only based on next.js and SSR+nodemailer.

I hope this clarify this a little bit. 

Kind regards.
